# Generated by Django 4.2.15 on 2024-09-16 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_menssagem_plataforma_msg_oquetemosparahoje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oquetemosparahoje',
            name='data',
        ),
        migrations.AddField(
            model_name='oquetemosparahoje',
            name='mensagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
