# Generated by Django 4.2.15 on 2024-09-16 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_remove_oquetemosparahoje_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menssagem_plataforma',
            name='mensagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
