# Generated by Django 4.2.15 on 2024-08-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_imagemindex2'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemindex2',
            name='contato',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
