# Generated by Django 4.2.15 on 2024-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_imgpublica_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgpublica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=101010),
            preserve_default=False,
        ),
    ]
