# Generated by Django 4.2.15 on 2024-10-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_imgpublica_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgpublica',
            name='created_at',
        ),
    ]
